#!/usr/bin/with-contenv bash

if [[ $UMASK == "" ]]; then
    UMASK=022
fi

umask $UMASK

cd /app || exit

if [[ $APP == "radarr" ]]; then
    echo "Starting Radarr..."
    exec s6-setuidgid hotio mono --debug Radarr.exe -nobrowser
fi

if [[ $APP == "sonarr" ]]; then
    echo "Starting Sonarr..."
    exec s6-setuidgid hotio mono --debug NzbDrone.exe -nobrowser
fi
