#!/usr/bin/with-contenv bash

echo '                                               '
echo '   _________      __  __                       '
echo '  /   _____/__ __|__|/  |______ ______________ '
echo '  \_____  \|  |  \  \   __\__  \\_  __ \_  __ \'
echo '  /        \  |  /  ||  |  / __ \|  | \/|  | \/'
echo ' /_______  /____/|__||__| (____  /__|   |__|   '
echo '         \/                    \/              '
echo '                                               '

echo "
-----------------------------------------------
GIVEN ENVIRONMENT
-----------------------------------------------
APP            | $APP
PUID           | $PUID
PGID           | $PGID
UMASK          | $UMASK
VERSION        | $VERSION
BACKUP         | $BACKUP
FILE           | $FILE
ARGS           | $ARGS
-----------------------------------------------
"

source /etc/env

echo "
RUNNING ENVIRONMENT
-----------------------------------------------
APP            | $APP
PUID           | $PUID
PGID           | $PGID
UMASK          | $UMASK
VERSION        | $VERSION
BACKUP         | $BACKUP
FILE           | $FILE
ARGS           | $ARGS
-----------------------------------------------
"

groupmod -o -g "$PGID" hotio
usermod -o -u "$PUID" hotio
