#!/usr/bin/with-contenv bash

echo '                                               '
echo '   _________      __  __                       '
echo '  /   _____/__ __|__|/  |______ ______________ '
echo '  \_____  \|  |  \  \   __\__  \\_  __ \_  __ \'
echo '  /        \  |  /  ||  |  / __ \|  | \/|  | \/'
echo ' /_______  /____/|__||__| (____  /__|   |__|   '
echo '         \/                    \/              '
echo '                                               '

echo "
-------------------------------------------
GIVEN ENVIRONMENT
-------------------------------------------
PUID           | $PUID
PGID           | $PGID
UMASK          | $UMASK
APP            | $APP
TZ             | $TZ
BRANCH         | $BRANCH
VERSION        | $VERSION
JACKETT_PROXY  | $JACKETT_PROXY
-------------------------------------------
"

PUID=${PUID:-1000}
PGID=${PGID:-1000}
UMASK=${UMASK:-022}
APP=${APP:-none}
TZ=${TZ:-America/New_York}
BRANCH=${BRANCH:-default}
VERSION=${VERSION:-default}
JACKETT_PROXY=${JACKETT_PROXY:-none}

if [[ -f /app.tar.gz ]]; then
    BRANCH=app.tar.gz
    VERSION=app.tar.gz
fi

echo "
RUNNING ENVIRONMENT
-------------------------------------------
PUID           | $PUID
PGID           | $PGID
UMASK          | $UMASK
APP            | $APP
TZ             | $TZ
BRANCH         | $BRANCH
VERSION        | $VERSION
JACKETT_PROXY  | $JACKETT_PROXY
-------------------------------------------
"

groupmod -o -g "$PGID" hotio
usermod -o -u "$PUID" hotio
