#!/usr/bin/with-contenv bash

PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" hotio
usermod -o -u "$PUID" hotio

echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u hotio)
User gid:    $(id -g hotio)
-------------------------------------
"
chown -R hotio:hotio /app
chown -R hotio:hotio /config
