#!/usr/bin/with-contenv bash

source /etc/env

rm -rf /app/*

if [[ $VERSION == "app.tar.gz" ]]; then
    echo "Installing user provided /app.tar.gz"
    tar xf /app.tar.gz -C /app --strip-components=1
else
    if [[ $APP == "radarr" ]]; then
        echo "Downloading & Installing Radarr..."
        if [[ $VERSION == "default" ]]; then
            jobid=$(curl -s "https://ci.appveyor.com/api/projects/galli-leo/radarr-usby1/branch/develop" | jq -r '.build.jobs[0].jobId')
        else
            jobid=$(curl -s "https://ci.appveyor.com/api/projects/galli-leo/radarr-usby1/build/${VERSION}" | jq -r '.build.jobs[0].jobId')
        fi
        
        filename=$(curl -s "https://ci.appveyor.com/api/buildjobs/${jobid}/artifacts" | jq -r '.[].fileName' | grep -o ".*Radarr.*.linux.tar.gz")
        curl -s -o /tmp/radarr.tar.gz -L "https://ci.appveyor.com/api/buildjobs/${jobid}/artifacts/${filename}"
            
        tar xf /tmp/radarr.tar.gz -C /app --strip-components=1
    fi

    if [[ $APP == "sonarr" ]]; then
        echo "Downloading & Installing Sonarr..."
        if [[ $VERSION == "default" ]] && [[ $BRANCH == "default" ]]; then
            curl -s -o /tmp/sonarr.tar.gz -L "http://download.sonarr.tv/v2/master/mono/NzbDrone.master.tar.gz"
        else
            curl -s -o /tmp/sonarr.tar.gz -L "http://download.sonarr.tv/v2/${BRANCH}/mono/NzbDrone.${BRANCH}.${VERSION}.mono.tar.gz"
        fi

        tar xf /tmp/sonarr.tar.gz -C /app --strip-components=1
    fi

    if [[ $APP == "jackett" ]]; then
        echo "Downloading & Installing Jackett..."
        if [[ $VERSION == "default" ]]; then
            jobid=$(curl -s "https://ci.appveyor.com/api/projects/camjac251/jackett/branch/master" | jq -r '.build.jobs[0].jobId')
        else
            jobid=$(curl -s "https://ci.appveyor.com/api/projects/camjac251/jackett/build/${VERSION}" | jq -r '.build.jobs[0].jobId')
        fi
        
        filename=$(curl -s "https://ci.appveyor.com/api/buildjobs/${jobid}/artifacts" | jq -r '.[].fileName' | grep -o ".*Mono.tar.gz")
        curl -s -o /tmp/jackett.tar.gz -L "https://ci.appveyor.com/api/buildjobs/${jobid}/artifacts/${filename}"

        tar xf /tmp/jackett.tar.gz -C /app --strip-components=1
    fi

    if [[ $APP == "nzbhydra" ]]; then
        echo "Downloading & Installing NZBHydra..."
        if [[ $VERSION == "default" ]]; then
            curl -s -o /tmp/nzbhydra.tar.gz -L "https://github.com/theotherp/nzbhydra/archive/master.tar.gz"
        else
            curl -s -o /tmp/nzbhydra.tar.gz -L "https://github.com/theotherp/nzbhydra/archive/$VERSION.tar.gz"
        fi
        
        tar xf /tmp/nzbhydra.tar.gz -C /app --strip-components=1
    fi
fi
 
rm -rf /tmp/*
chown -R hotio:hotio /app
