#!/usr/bin/with-contenv bash

source /etc/env

rm -rf /app/*

if [[ $FILE != "none" ]]; then
    tar xzf $FILE -C /app --strip-components=1
else
    if [[ $APP == "radarr" ]]; then
        case $VERSION in
            stable)     url=$(curl -s https://api.github.com/repos/radarr/radarr/releases | jq -r .[0].assets[1].browser_download_url)
                        ;;
            unstable)   jobid=$(curl -s https://ci.appveyor.com/api/projects/galli-leo/radarr-usby1/branch/develop | jq -r '.build.jobs[0].jobId')
                        filename=$(curl -s https://ci.appveyor.com/api/buildjobs/${jobid}/artifacts | jq -r '.[].fileName' | grep -o ".*Radarr.*.linux.tar.gz")
                        url=https://ci.appveyor.com/api/buildjobs/${jobid}/artifacts/${filename}
                        ;;
            *)          jobid=$(curl -s https://ci.appveyor.com/api/projects/galli-leo/radarr-usby1/build/${VERSION} | jq -r '.build.jobs[0].jobId')
                        filename=$(curl -s https://ci.appveyor.com/api/buildjobs/${jobid}/artifacts | jq -r '.[].fileName' | grep -o ".*Radarr.*.linux.tar.gz")
                        url=https://ci.appveyor.com/api/buildjobs/${jobid}/artifacts/${filename}
                        ;;
        esac
        curl -s --fail -o /tmp/app.tar.gz -L $url && tar xzf /tmp/app.tar.gz -C /app --strip-components=1 && rm /tmp/app.tar.gz
    fi

    if [[ $APP == "sonarr" ]]; then
        case $VERSION in
            stable)     url=http://download.sonarr.tv/v2/master/mono/NzbDrone.master.tar.gz
                        ;;
            unstable)   url=http://download.sonarr.tv/v2/develop/mono/NzbDrone.develop.tar.gz
                        ;;
            *)          if curl -s --fail --head -o /dev/null -L http://download.sonarr.tv/v2/master/mono/NzbDrone.master.${VERSION}.mono.tar.gz; then
                            url=http://download.sonarr.tv/v2/master/mono/NzbDrone.master.${VERSION}.mono.tar.gz
                        else
                            url=http://download.sonarr.tv/v2/develop/mono/NzbDrone.develop.${VERSION}.mono.tar.gz
                        fi
                        ;;
        esac
        curl -s --fail -o /tmp/app.tar.gz -L $url && tar xzf /tmp/app.tar.gz -C /app --strip-components=1 && rm /tmp/app.tar.gz
    fi

    if [[ $APP == "jackett" ]]; then
        case $VERSION in
            stable)     url=$(curl -s https://api.github.com/repos/jackett/jackett/releases/latest | jq -r .assets[0].browser_download_url)
                        ;;
            unstable)   url=$(curl -s https://api.github.com/repos/jackett/jackett/releases | jq -r .[0].assets[0].browser_download_url)
                        ;;
            *)          url=$(curl -s https://api.github.com/repos/jackett/jackett/releases/tags/v$VERSION | jq -r .assets[0].browser_download_url)
                        ;;
        esac
        curl -s --fail -o /tmp/app.tar.gz -L $url && tar xzf /tmp/app.tar.gz -C /app --strip-components=1 && rm /tmp/app.tar.gz
    fi

    if [[ $APP == "nzbhydra" ]]; then
        case $VERSION in
            stable)     url=$(curl -s https://api.github.com/repos/theotherp/nzbhydra/releases/latest | jq -r .tarball_url)
                        ;;
            unstable)   url=https://github.com/theotherp/nzbhydra/archive/master.tar.gz
                        ;;
            *)          url=https://github.com/theotherp/nzbhydra/archive/$VERSION.tar.gz
                        ;;
        esac
        curl -s --fail -o /tmp/app.tar.gz -L $url && tar xzf /tmp/app.tar.gz -C /app --strip-components=1 && rm /tmp/app.tar.gz
    fi
fi

chown -R hotio:hotio /app
