#!/usr/bin/with-contenv bash

if [[ $UMASK == "" ]]; then
    UMASK=022
fi

if [[ $APP == "radarr" ]]; then
    mkdir -p /etc/services.d/radarr
    echo "#!/usr/bin/with-contenv bash" >> /etc/services.d/radarr/run
    echo "umask $UMASK" >> /etc/services.d/radarr/run
    echo "cd /app || exit" >> /etc/services.d/radarr/run
    echo "exec s6-setuidgid hotio mono --debug Radarr.exe -nobrowser" >> /etc/services.d/radarr/run
fi

if [[ $APP == "sonarr" ]]; then
    mkdir -p /etc/services.d/sonarr
    echo "#!/usr/bin/with-contenv bash" >> /etc/services.d/sonarr/run
    echo "umask $UMASK" >> /etc/services.d/sonarr/run
    echo "cd /app || exit" >> /etc/services.d/sonarr/run
    echo "exec s6-setuidgid hotio mono --debug NzbDrone.exe -nobrowser" >> /etc/services.d/sonarr/run
fi
