#!/usr/bin/with-contenv bash

if [[ $APP == "radarr" ]]; then
    config=/config/Radarr

    [[ -e $config/nzbdrone.pid ]] && rm -rf $config/nzbdrone.pid

    if [[ -f $config/config.xml ]]; then
        sed -i 's/<Port>.*<\/Port>/<Port>8080<\/Port>/g' $config/config.xml
    else
        mkdir -p $config
        echo "<Config><Port>8080</Port></Config>" > $config/config.xml
    fi
fi

if [[ $APP == "sonarr" ]]; then
    config=/config/NzbDrone

    [[ -e $config/nzbdrone.pid ]] && rm -rf $config/nzbdrone.pid

    if [[ -f $config/config.xml ]]; then
        sed -i 's/<Port>.*<\/Port>/<Port>8080<\/Port>/g' $config/config.xml
    else
        mkdir -p $config
        echo "<Config><Port>8080</Port></Config>" > $config/config.xml
    fi
fi

chown -R hotio:hotio /config
